spring:
  application:
    name: clientmanagement-svc
  config:
    import: "optional:configserver:https://microservices-project.onrender.com"
    #      import: "optional:configserver:http://localhost:8089"
