server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: https://microservices-project.onrender.com
          predicates:
            - Path=/eureka/web
          filters: SetPath=/
        - id: discovery-server-static
          uri: https://microservices-project.onrender.com
          predicates:
            - Path=/eureka/**
        - id: jwt-authentication-svc
          uri: lb://jwt-authentication-svc
          predicates:
            - Path=/v1/api/authentication/**
          filters: JwtAuthFilter
        - id: clientmanagement-service
          uri: lb://clientmanagement-svc
          predicates:
            - Path=/v1/api/clients/**
          filters: JwtAuthFilter

eureka:
  client:
    service-url:
      defaultZone: https://microservices-project.onrender.com/eureka/
