server:
  port: 8084

spring:
  application:
    name: clientmanagement-svc
  datasource:
    url: jdbc:postgresql://dpg-cuif7m56l47c73aesgt0-a.oregon-postgres.render.com:5432/microservices_app
    username: postgre
    password: yJeef8OuauaIHbX8qZiNFhACmiJ0jusk
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/